version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - "starefossen"
  - package-ecosystem: "github-actions"
    directory: "/" # must be root (ref. docs)
    schedule:
      interval: "weekly"
    reviewers:
      - "starefossen"
  - package-ecosystem: "pip" # poetry / pyproject
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - "starefossen"
  - package-ecosystem: "terraform"
    directory: "/terraform/"
    schedule:
      interval: "weekly"
    reviewers:
      - "starefossen"
